---
- name: Reset Kubernetes cluster
  hosts: kubernetes_cluster
  gather_facts: true
  become: true
  tasks:
    - name: Reset kubeadm
      ansible.builtin.command: kubeadm reset --force
      failed_when: false

    - name: Stop kubelet
      ansible.builtin.systemd:
        name: kubelet
        state: stopped
        enabled: false

    - name: Remove Kubernetes packages
      ansible.builtin.apt:
        name:
          - kubeadm
          - kubelet
          - kubectl
        state: absent
      when: ansible_os_family == "Debian"

    - name: Remove Kubernetes directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/kubernetes
        - /var/lib/kubelet
        - /var/lib/etcd
        - "{{ ansible_user_dir }}/.kube"

- name: Revert changes to Proxmox cluster
  hosts: proxmox
  gather_facts: true
  become: true
  remote_user: "{{ proxmox_lxc_ssh_user }}"
  roles:
    - role: reset_proxmox_lxc
      when: proxmox_lxc_configure
