---
# Fedora/RedHat specific tasks
- name: Update dnf cache
  dnf:
    update_cache: yes

- name: Install required packages for Fedora/RedHat
  dnf:
    name:
      - dnf-plugins-core
      - container-selinux
      - device-mapper-persistent-data
      - lvm2
    state: present

- name: Configure system settings for Kubernetes
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: /etc/sysctl.d/99-kubernetes.conf
  with_items:
    - { name: 'net.bridge.bridge-nf-call-iptables', value: '1' }
    - { name: 'net.ipv4.ip_forward', value: '1' }
    - { name: 'net.bridge.bridge-nf-call-ip6tables', value: '1' }

- name: Disable SELinux
  selinux:
    state: disabled
