---
# Configure containerd to use private registry
- name: Ensure /etc/containerd directory exists
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    mode: '0755'

- name: Create containerd config.toml
  ansible.builtin.template:
    src: config.toml.j2
    dest: /etc/containerd/config.toml
    mode: '0644'
  notify: Restart containerd

# Create Kubernetes secret for private registry
- name: Create registry credentials secret
  when: custom_registries | bool
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: registry-credentials
        namespace: default
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ custom_registries_yaml | to_json | b64encode }}"

- name: Add registry credentials to default service account
  when: custom_registries | bool
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: default
        namespace: default
      imagePullSecrets:
        - name: registry-credentials
